version: '2.3'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: mysql
    container_name: django-template-mysql

  djang_app:
    extends:
      file: docker-compose.common.yml
      service: django_app
    container_name: django-app-develop
    ports:
      - ${DJANGO_PORT}:8000
    environment:
      - DJANGO_CONFIGURATION=LocalMySQL
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db_dev
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: /bin/bash
    tty: true
    env_file: .env
    depends_on:
      - db
  mkdocs:
    extends:
      file: docker-compose.common.yml
      service: mkdocs
    container_name: django-template-docs
