# Generated by Django 2.1.15 on 2020-07-01 17:14

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('deleted_at', model_utils.fields.MonitorField(default=None, editable=False, monitor='is_removed', when={True})),
                ('name', models.CharField(default='no title', max_length=120, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('deleted_at', model_utils.fields.MonitorField(default=None, editable=False, monitor='is_removed', when={True})),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'アイテム種類',
                'verbose_name_plural': 'アイテム種類',
            },
        ),
        migrations.CreateModel(
            name='ItemTypeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_type_relations', to='neo_soft_delete.Item')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_soft_delete.ItemType')),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('deleted_at', model_utils.fields.MonitorField(default=None, editable=False, monitor='is_removed', when={True})),
                ('name', models.CharField(default='no title', max_length=120, verbose_name='name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_soft_delete.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubItemNoSoftDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no title', max_length=120, verbose_name='name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_soft_delete.Item')),
            ],
        ),
    ]
