# Generated by Django 2.1.15 on 2020-07-01 17:15

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neo_soft_delete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deleted_at',
            field=model_utils.fields.MonitorField(default=None, editable=False, monitor='is_removed', null=True, when={True}),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='deleted_at',
            field=model_utils.fields.MonitorField(default=None, editable=False, monitor='is_removed', null=True, when={True}),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='deleted_at',
            field=model_utils.fields.MonitorField(default=None, editable=False, monitor='is_removed', null=True, when={True}),
        ),
    ]
