# Generated by Django 2.2.12 on 2020-05-11 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domain',
            new_name='Tenant',
        ),
    ]
