# Generated by Django 2.1.8 on 2019-06-27 02:22

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, help_text='アップロード可能な最大ファイルサイズは3Bです. 拡張子は次のいずれかが使用できます {"pdf", "jpeg", "jpg", "png"}.', null=True, upload_to=articles.models.upload_to_uuid4_name, validators=[articles.models.FileValidator(allowed_extensions=('pdf', 'jpeg', 'jpg', 'png'), max_bytes=3)], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='no title', max_length=120, validators=[articles.models.MyCharValidator()], verbose_name='タイトル'),
        ),
    ]
