# Generated by Django 2.1.15 on 2019-12-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0002_auto_20190708_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='no title', max_length=120, verbose_name='名前'),
        ),
    ]
