# Generated by Django 2.2.6 on 2019-10-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190708_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('publish', '公開'), ('unpublish', '非公開')], default='unpublish', help_text='null の場合は, 非公開(下書き)', max_length=32, null=True, verbose_name='公開ステータス'),
        ),
    ]
