# Generated by Django 2.2.4 on 2019-09-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190708_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='NeoTagRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neo_tag_set', to='articles.Article')),
                ('neo_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.NeoTag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='neo_tags',
            field=models.ManyToManyField(through='articles.NeoTagRel', to='articles.NeoTag'),
        ),
    ]
